import { theme } from "@/config/theme";
import type { CSSProperties } from "react";

export const ARTWORK_SIZE = 1080;

export const artwork = {
  colors: {
    background: theme.brandPrimary,
    secondary: theme.brandSecondary,
    accent: theme.accent,
    text: "#ffffff",
    subtleText: "rgba(255, 255, 255, 0.55)",
    rule: "rgba(255, 255, 255, 0.4)",
  },
  header: {
    x: 81,
    y: 81,
    brandFontSize: 24,
    editionRight: 81,
    editionTop: 69,
    editionPaddingX: 18,
    editionHeight: 42,
    editionFontSize: 16,
  },
  portrait: { x: 507.6, y: 270, width: 507.6, height: 810 },
  copy: {
    x: 81,
    y: 600,
    width: 594,
    labelFontSize: 20,
    labelLineHeight: 20,
    labelGap: 22,
    nameGap: 8,
    roleGap: 20,
    ruleWidth: 68,
    ruleHeight: 4,
    ruleGap: 24,
  },
  footer: {
    left: 81,
    right: 81,
    ruleY: 976.6,
    textY: 996.6,
    fontSize: 14,
    badgeX: 951,
    badgeY: 988.6,
    badgeSize: 48,
    badgeFontSize: 16,
  },
  decorations: {
    ring: { x: 874.8, y: 216, size: 648, border: 58 },
    circle: { x: 1058.4, y: 1155.6, size: 550.8 },
  },
  typography: {
    sans: "Arial, Helvetica, sans-serif",
    serif: 'Georgia, "Times New Roman", serif',
    name: { size: 49, weight: 500, lineHeight: 50, letterSpacing: -1.96 },
    role: { size: 13, weight: 400, lineHeight: 19 },
    topic: { size: 17, weight: 700, lineHeight: 22 },
  },
} as const;

export const artworkCssVariables = {
  "--artwork-size": `${ARTWORK_SIZE}px`,
  "--header-x": `${artwork.header.x}px`,
  "--header-y": `${artwork.header.y}px`,
  "--brand-font-size": `${artwork.header.brandFontSize}px`,
  "--edition-right": `${artwork.header.editionRight}px`,
  "--edition-top": `${artwork.header.editionTop}px`,
  "--edition-padding-x": `${artwork.header.editionPaddingX}px`,
  "--edition-height": `${artwork.header.editionHeight}px`,
  "--edition-font-size": `${artwork.header.editionFontSize}px`,
  "--portrait-x": `${artwork.portrait.x}px`,
  "--portrait-y": `${artwork.portrait.y}px`,
  "--portrait-width": `${artwork.portrait.width}px`,
  "--portrait-height": `${artwork.portrait.height}px`,
  "--copy-x": `${artwork.copy.x}px`,
  "--copy-y": `${artwork.copy.y}px`,
  "--copy-width": `${artwork.copy.width}px`,
  "--label-font-size": `${artwork.copy.labelFontSize}px`,
  "--label-line-height": `${artwork.copy.labelLineHeight}px`,
  "--label-gap": `${artwork.copy.labelGap}px`,
  "--name-gap": `${artwork.copy.nameGap}px`,
  "--role-gap": `${artwork.copy.roleGap}px`,
  "--topic-rule-width": `${artwork.copy.ruleWidth}px`,
  "--topic-rule-height": `${artwork.copy.ruleHeight}px`,
  "--topic-rule-gap": `${artwork.copy.ruleGap}px`,
  "--name-font-size": `${artwork.typography.name.size}px`,
  "--name-line-height": `${artwork.typography.name.lineHeight}px`,
  "--name-letter-spacing": `${artwork.typography.name.letterSpacing}px`,
  "--role-font-size": `${artwork.typography.role.size}px`,
  "--role-line-height": `${artwork.typography.role.lineHeight}px`,
  "--topic-font-size": `${artwork.typography.topic.size}px`,
  "--topic-line-height": `${artwork.typography.topic.lineHeight}px`,
  "--footer-left": `${artwork.footer.left}px`,
  "--footer-right": `${artwork.footer.right}px`,
  "--footer-rule-y": `${artwork.footer.ruleY}px`,
  "--footer-text-y": `${artwork.footer.textY}px`,
  "--footer-font-size": `${artwork.footer.fontSize}px`,
  "--badge-x": `${artwork.footer.badgeX}px`,
  "--badge-y": `${artwork.footer.badgeY}px`,
  "--badge-size": `${artwork.footer.badgeSize}px`,
  "--badge-font-size": `${artwork.footer.badgeFontSize}px`,
  "--ring-x": `${artwork.decorations.ring.x}px`,
  "--ring-y": `${artwork.decorations.ring.y}px`,
  "--ring-size": `${artwork.decorations.ring.size}px`,
  "--ring-border": `${artwork.decorations.ring.border}px`,
  "--circle-x": `${artwork.decorations.circle.x}px`,
  "--circle-y": `${artwork.decorations.circle.y}px`,
  "--circle-size": `${artwork.decorations.circle.size}px`,
} as CSSProperties;
